class Stats:
    objectives_stolen: int
    brawl_ball_shots_on_goal: int
    brawl_ball_shots_saved: int
    healing_done: int
    damage_dealt: int
    average_latency: int
    damage_received: int
    kills: int
    deaths: int
    total_damage_to_safe: int
    total_damage_to_pets: int
    siege_damage_to_robot: int
    siege_bolts_collected: int
    brawl_ball_goals_scored: int
    gem_grab_gems_collected: int
    gem_grab_gems_lost: int
    bounty_stars_gained: int
    bounty_stars_lost: int
    super_used_count: int
    gadget_used_count: int
    bounty_picked_middle_star: int
    match_end_kill_streak: int
    max_kill_streak: int
    hot_zone_inside_zone_percentage: int
    healing_done_to_self: int
    healing_done_to_team_mates: int
    objectives_recovered: int